In [2]:
import pandas as pd

In [3]:
facilities = pd.read_csv('../../views/facility_master_v6.csv')
facilities.head()

,source_id,source_name,source_type,iso3_country,sector,subsector,lat,lon,capacity_units,capacity,...,PV fixed-axis_Variable O&M_2025_$/MWh,PV fixed-axis_Variable O&M_2030_$/MWh,PV fixed-axis_BNEF_LCOE_2025_$/MWh,PV fixed-axis_BNEF_LCOE_2030_$/MWh,Coal_BNEF_LCOE_2025_$/MWh,Coal_BNEF_LCOE_2030_$/MWh,CCGT_BNEF_LCOE_2025_$/MWh,CCGT_BNEF_LCOE_2030_$/MWh,PV fixed-axis_calc_LCOE_2025_$/MWh,PV fixed-axis_calc_LCOE_2030_$/MWh
0,25454443,Utraula power station,coal,IND,power,electricity-generation,27.3454,82.3165,MW,90.0,...,0.0,0.0,25.14,19.48,57.04,58.59,95.34,90.95,24.633995,22.401488
1,25454888,Visakhapatnam Sarda power station,coal,IND,power,electricity-generation,17.9415,83.2232,MW,84.0,...,0.0,0.0,25.14,19.48,57.04,58.59,95.34,90.95,26.230885,23.853657
2,4406831,Warana Sugar power station,biomass,IND,power,electricity-generation,16.8622,74.1984,MW,44.0,...,0.0,0.0,25.14,19.48,57.04,58.59,95.34,90.95,26.129490,23.761451
3,40697975,Yadadri power station,coal,IND,power,electricity-generation,16.7082,79.5812,MW,0.0,...,0.0,0.0,25.14,19.48,57.04,58.59,95.34,90.95,26.604520,24.193430
4,40698636,Castlelost Flexgen power station,gas,IRL,power,electricity-generation,53.3994,-7.3207,MW,55.0,...,0.0,0.0,41.62,35.54,229.50,223.12,131.97,132.43,54.324318,47.086209

In [4]:
facilities = facilities[['source_id', 'source_name', 'source_type', 'iso3_country', 'Region', 'sector','subsector', 'lat', 'lon', 'co2e_20yr','grassland_km2_5','bare_sparse_km2_5','grassland_km2_15', 'bare_sparse_km2_15']]
facilities.head()

KeyError: "['Region'] not in index"

In [ ]:
facilities['potential_mw_solar_5'] = (facilities['grassland_km2_5'] + facilities['bare_sparse_km2_5']) * 
facilities['potential_mw_solar_15'] = (facilities['grassland_km2_15'] + facilities['bare_sparse_km2_15'])*

In [6]:
facilities

,source_id,source_name,source_type,iso3_country,Region,sector,subsector,lat,lon,co2e_20yr,grassland_km2_5,bare_sparse_km2_5,grassland_km2_15,bare_sparse_km2_15
0,110,Edge Moor,"gas, oil",USA,United States,power,electricity-generation,39.741200,-75.505500,2.183800e+06,6.080356,0.992276,72.540952,3.354928
1,818,Hibbing,coal,USA,United States,power,electricity-generation,47.429400,-92.935000,1.030160e+05,7.996098,6.006056,91.925563,25.330229
2,923,HF Lee and Wayne County power complex,"gas, oil, coal",USA,United States,power,electricity-generation,35.373200,-78.089000,2.306700e+06,9.191251,0.519862,93.162991,2.570843
3,1193,Baconton Power Plant,gas,USA,United States,power,electricity-generation,31.386900,-84.080000,2.920300e+05,8.123656,0.047497,86.796246,0.363341
4,1376,RAS AL-KHAFJI ARAMCO,"gas, oil",SAU,NaN,power,electricity-generation,28.413000,48.530500,4.348400e+05,0.026814,10.387924,0.236529,201.011634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44470,48193122,Zunyi Prefecture City,Refinery,CHN,China,manufacturing,aluminum,28.167600,107.086536,3.411168e+06,0.210062,0.000000,4.061433,0.176183
44471,48306352,ArcelorMittal Calvert,EAF,USA,United States,manufacturing,iron-and-steel,31.148446,-87.990521,2.584982e+05,4.695847,0.775466,30.134794,1.507608
44472,48306423,Hybar Arkansas steel plant,EAF,USA,United States,manufacturing,iron-and-steel,35.686814,-89.961981,2.778392e+04,7.475430,0.739563,23.357564,2.242821
44473,48306440,ESM Mutún steel plant,DRI-EAF,BOL,NaN,manufacturing,iron-and-steel,-19.137325,-57.880605,1.102623e+05,6.408138,0.010149,25.491904,0.212261
44474,48306442,Rungta Mines Karakhendra Steel Plant,BF/BOF,IND,India,manufacturing,iron-and-steel,22.140174,85.414616,3.951626e+05,3.595103,0.597233,30.911115,5.340883

In [10]:
facilities[:10].to_csv('sites.csv', index=False)